[package]
name = "find"
version = "0.1.0"
edition = "2021"
authors = ["Chad Baker"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5"
clap = { version = "3.2.6", features = ["derive"] }
clap_complete_command = "0.3.4"
